export const data = [
  {
    id: "16",
    courseCode: "7000011529",
    courseName: "احتمال 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "6789",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "10",
    submitted: "",
    classTime: "چهارشنبه  از 18:00 تا 20:15",
    classExam: "1403/04/11 از 08:00 تا 10:00",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "97",
    courseCode: "6117166717",
    courseName: "احتمال 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7071",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "30",
    submitted: "",
    classTime: "چهارشنبه  از 18:00 تا 20:15",
    classExam: "1403/04/11 از 08:00 تا 10:00",
    teacher: "علی مالکی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1402",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "98",
    courseCode: "6117166717",
    courseName: "احتمال 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7070",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "چهارشنبه  از 15:30 تا 17:45",
    classExam: "1403/04/11 از 08:00 تا 10:00",
    teacher: "علی مالکی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1402",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "99",
    courseCode: "6117166717",
    courseName: "احتمال 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7069",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "چهارشنبه  از 13:00 تا 15:15",
    classExam: "1403/04/11 از 08:00 تا 10:00",
    teacher: "علی مالکی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1402",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "38",
    courseCode: "1393105510",
    courseName: "اصول سیستم های عامل",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "8558",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "0",
    submitted: "",
    classTime: "",
    classExam: "1403/04/03 از 13:30 تا 15:30",
    teacher: "محمد مهدی حسنی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "39",
    courseCode: "1393105510",
    courseName: "اصول سیستم های عامل",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "6556",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "4",
    submitted: "",
    classTime: "يكشنبه  از 13:00 تا 16:00",
    classExam: "1403/04/03 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "1",
    courseCode: "6033105514",
    courseName: "اصول سیستمهای کامپیوتری",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "5963",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "1",
    submitted: "",
    classTime: "شنبه  از 13:00 تا 16:00",
    classExam: "1403/04/14 از 08:00 تا 10:00",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "33",
    courseCode: "6033112863",
    courseName: "بهینه سازی خطی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "8998",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "24",
    submitted: "",
    classTime: "دوشنبه  از 15:30 تا 17:45",
    classExam: "1403/04/12 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "32",
    courseCode: "1393114001",
    courseName: "پایگاه‌داده‌ها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "9669",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "15",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/14 از 08:00 تا 10:00",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "93",
    courseCode: "2661114001",
    courseName: "پایگاه‌داده‌ها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7075",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "پنج شنبه  از 10:00 تا 12:15",
    classExam: "1403/04/14 از 08:00 تا 10:00",
    teacher: "رضا رضایی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1205",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "94",
    courseCode: "2661114001",
    courseName: "پایگاه‌داده‌ها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7074",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "25",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/14 از 08:00 تا 10:00",
    teacher: "رضا رضایی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1205",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "12",
    courseCode: "6033114704",
    courseName: "پروژه",
    courseType: "عملي",
    theoreticaUnits: "0",
    practicalUnits: "3",
    classCode: "2369",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "5",
    submitted: "",
    classTime: "",
    classExam: "",
    teacher: "حسام محزون",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "20",
    courseCode: "6033114704",
    courseName: "پروژه",
    courseType: "عملي",
    theoreticaUnits: "0",
    practicalUnits: "3",
    classCode: "0203",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "4",
    submitted: "",
    classTime: "",
    classExam: "",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "27",
    courseCode: "6033114704",
    courseName: "پروژه",
    courseType: "عملي",
    theoreticaUnits: "0",
    practicalUnits: "3",
    classCode: "9636",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "8",
    submitted: "",
    classTime: "",
    classExam: "",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "28",
    courseCode: "6033114704",
    courseName: "پروژه",
    courseType: "عملي",
    theoreticaUnits: "0",
    practicalUnits: "3",
    classCode: "9856",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "6",
    submitted: "",
    classTime: "",
    classExam: "",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "40",
    courseCode: "7000015321",
    courseName: "پروژه",
    courseType: "عملي",
    theoreticaUnits: "0",
    practicalUnits: "3",
    classCode: "3214",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "2",
    submitted: "",
    classTime: "",
    classExam: "",
    teacher: "مریم مزدارانی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "41",
    courseCode: "7000015321",
    courseName: "پروژه",
    courseType: "عملي",
    theoreticaUnits: "0",
    practicalUnits: "3",
    classCode: "4561",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "8",
    submitted: "",
    classTime: "",
    classExam: "",
    teacher: "محمد غلامیان",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "42",
    courseCode: "7000015321",
    courseName: "پروژه",
    courseType: "عملي",
    theoreticaUnits: "0",
    practicalUnits: "3",
    classCode: "2589",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "4",
    submitted: "",
    classTime: "",
    classExam: "",
    teacher: "دکتر اباصلت بداغی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "43",
    courseCode: "7000015321",
    courseName: "پروژه",
    courseType: "عملي",
    theoreticaUnits: "0",
    practicalUnits: "3",
    classCode: "1234",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "8",
    submitted: "",
    classTime: "",
    classExam: "",
    teacher: "سعید صیدانلو",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "44",
    courseCode: "7000015321",
    courseName: "پروژه",
    courseType: "عملي",
    theoreticaUnits: "0",
    practicalUnits: "3",
    classCode: "5432",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "5",
    submitted: "",
    classTime: "",
    classExam: "",
    teacher: "حسام محزون",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "45",
    courseCode: "7000015321",
    courseName: "پروژه",
    courseType: "عملي",
    theoreticaUnits: "0",
    practicalUnits: "3",
    classCode: "9876",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "1",
    submitted: "",
    classTime: "",
    classExam: "",
    teacher: "امیر موسیوند",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "15",
    courseCode: "6033121760",
    courseName: "جبر خطی عددی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "6960",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "1",
    submitted: "",
    classTime: "دوشنبه  از 13:00 تا 15:15",
    classExam: "1403/04/12 از 10:30 تا 12:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "9",
    courseCode: "6117165140",
    courseName: "ریاضی عمومی 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "8787",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "چهارشنبه  از 13:00 تا 15:15",
    classExam: "1403/04/14 از 10:30 تا 12:30",
    teacher: "لیلا گرامی معظم",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "نيمسال ورود[نیمسال دوم سال تحصیلی 1403-1402]",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "10",
    courseCode: "6117165140",
    courseName: "ریاضی عمومی 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "43430",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "دوشنبه  از 07:30 تا 09:45",
    classExam: "1403/04/14 از 10:30 تا 12:30",
    teacher: "لیلا گرامی معظم",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1409",
    licence: "نيمسال ورود[نیمسال دوم سال تحصیلی 1403-1402]",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "18",
    courseCode: "6117165140",
    courseName: "ریاضی عمومی 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "3737",
    className: "استد: مجید حسنی",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "49",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/14 از 10:30 تا 12:30",
    teacher: "پخشان اسپوکه",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "31",
    courseCode: "6117165140",
    courseName: "ریاضی عمومی 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7980",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "سه شنبه  از 15:30 تا 17:45",
    classExam: "1403/04/14 از 10:30 تا 12:30",
    teacher: "مریم مزدارانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1205",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "51",
    courseCode: "6117165140",
    courseName: "ریاضی عمومی 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "3001",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "چهارشنبه  از 07:30 تا 09:45",
    classExam: "1403/04/14 از 10:30 تا 12:30",
    teacher: "لیلا گرامی معظم",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "79",
    courseCode: "6117165140",
    courseName: "ریاضی عمومی 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1070",
    className: "علوم کامپیوتر",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "46",
    submitted: "",
    classTime: "شنبه  از 18:00 تا 20:15",
    classExam: "1403/04/14 از 10:30 تا 12:30",
    teacher: "سعید صیدانلو",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "80",
    courseCode: "6117165140",
    courseName: "ریاضی عمومی 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1069",
    className: "علوم کامپیوتر",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "48",
    submitted: "",
    classTime: "شنبه  از 15:30 تا 17:45",
    classExam: "1403/04/14 از 10:30 تا 12:30",
    teacher: "سعید صیدانلو",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "81",
    courseCode: "6117165140",
    courseName: "ریاضی عمومی 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1066",
    className: "مجید حسنی",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "48",
    submitted: "",
    classTime: "شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/14 از 10:30 تا 12:30",
    teacher: "مژگان علی عسگری",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1402",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "8",
    courseCode: "55001",
    courseName: "ریاضیات پایه(پیش نیاز دانشگاهی)",
    courseType: "نظري",
    theoreticaUnits: "2",
    practicalUnits: "0",
    classCode: "7873",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "دوشنبه  از 11:00 تا 12:30",
    classExam: "1403/04/03 از 10:30 تا 12:30",
    teacher: "معصومه چراغی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1210",
    licence: "نيمسال ورود[نیمسال دوم سال تحصیلی 1403-1402]",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "14",
    courseCode: "55001",
    courseName: "ریاضیات پایه(پیش نیاز دانشگاهی)",
    courseType: "نظري",
    theoreticaUnits: "2",
    practicalUnits: "0",
    classCode: "3636",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "چهارشنبه  از 18:45 تا 20:15",
    classExam: "1403/04/03 از 10:30 تا 12:30",
    teacher: "مهدي مولوي",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "نيمسال ورود[نیمسال دوم سال تحصیلی 1403-1402]",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "46",
    courseCode: "55001",
    courseName: "ریاضیات پایه(پیش نیاز دانشگاهی)",
    courseType: "نظري",
    theoreticaUnits: "2",
    practicalUnits: "0",
    classCode: "1233",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "49",
    submitted: "",
    classTime: "دوشنبه  از 18:00 تا 19:30",
    classExam: "1403/04/03 از 10:30 تا 12:30",
    teacher: "معصومه چراغی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1401",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "58",
    courseCode: "55001",
    courseName: "ریاضیات پایه(پیش نیاز دانشگاهی)",
    courseType: "نظري",
    theoreticaUnits: "2",
    practicalUnits: "0",
    classCode: "1217",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "سه شنبه  از 13:00 تا 14:30",
    classExam: "1403/04/03 از 10:30 تا 12:30",
    teacher: "سیما سعاد ت اختر",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "59",
    courseCode: "55001",
    courseName: "ریاضیات پایه(پیش نیاز دانشگاهی)",
    courseType: "نظري",
    theoreticaUnits: "2",
    practicalUnits: "0",
    classCode: "1216",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "سه شنبه  از 11:00 تا 12:30",
    classExam: "1403/04/03 از 10:30 تا 12:30",
    teacher: "سیما سعاد ت اختر",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "13",
    courseCode: "1393129684",
    courseName: "ریاضی‌ عمومی‌ 1",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "9632",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "1",
    submitted: "",
    classTime: "شنبه  از 18:00 تا 20:15",
    classExam: "1403/04/14 از 10:30 تا 12:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "52",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1342",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "41",
    submitted: "",
    classTime: "شنبه  از 15:30 تا 17:45",
    classExam: "1403/04/17 از 10:30 تا 12:30",
    teacher: "یاسر رستمی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "64",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1112",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "0",
    submitted: "",
    classTime: "",
    classExam: "1403/04/17 از 10:30 تا 12:30",
    teacher: "سعید صیدانلو",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "65",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1111",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "0",
    submitted: "",
    classTime: "",
    classExam: "1403/04/17 از 10:30 تا 12:30",
    teacher: "سعید صیدانلو",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "66",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1110",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 10:00 تا 12:15",
    classExam: "1403/04/17 از 10:30 تا 12:30",
    teacher: "لیلا گرامی معظم",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1418",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "67",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1109",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "0",
    submitted: "",
    classTime: "دوشنبه  از 07:30 تا 09:45",
    classExam: "1403/04/17 از 10:30 تا 12:30",
    teacher: "مژگان علی عسگری",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "75",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10790",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "35",
    submitted: "",
    classTime: "پنج شنبه  از 15:30 تا 17:45",
    classExam: "1403/04/17 از 10:30 تا 12:30",
    teacher: "نادر بیرانوند",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1402",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "76",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1077",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "پنج شنبه  از 13:00 تا 15:15",
    classExam: "1403/04/17 از 10:30 تا 12:30",
    teacher: "نادر بیرانوند",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1402",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "77",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1076",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 10:00 تا 12:15",
    classExam: "1403/04/09 از 10:30 تا 12:30",
    teacher: "بهروز شجاعی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1402",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "78",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1075",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 07:30 تا 09:45",
    classExam: "1403/04/09 از 10:30 تا 12:30",
    teacher: "بهروز شجاعی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "24",
    courseCode: "6033130328",
    courseName: "ریز پردازنده 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "3023",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "6",
    submitted: "",
    classTime: "دوشنبه  از 13:00 تا 15:15",
    classExam: "1403/04/14 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "29",
    courseCode: "1393131453",
    courseName: "زبان های برنامه سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "2598",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "8",
    submitted: "",
    classTime: "سه شنبه  از 13:00 تا 15:15",
    classExam: "1403/04/02 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "49",
    courseCode: "6117131453",
    courseName: "زبان های برنامه سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1145",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "سه شنبه  از 13:00 تا 15:15",
    classExam: "1403/04/02 از 13:30 تا 15:30",
    teacher: "مناف شریف زاده",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1205",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "11",
    courseCode: "7000003408",
    courseName: "زیست شناسی عمومی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "3232",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "1",
    submitted: "",
    classTime: "شنبه  از 13:00 تا 15:15",
    classExam: "1403/04/04 از 10:30 تا 12:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "56",
    courseCode: "3762131982",
    courseName: "زیست شناسی عمومی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1235",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "46",
    submitted: "",
    classTime: "سه شنبه  از 15:30 تا 17:45",
    classExam: "1403/04/04 از 10:30 تا 12:30",
    teacher: "ارا منطقي تفرشي",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1401",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "57",
    courseCode: "3762131982",
    courseName: "زیست شناسی عمومی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1234",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "48",
    submitted: "",
    classTime: "سه شنبه  از 18:00 تا 20:15",
    classExam: "1403/04/04 از 10:30 تا 12:30",
    teacher: "ارا منطقي تفرشي",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1401",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "68",
    courseCode: "3762131982",
    courseName: "زیست شناسی عمومی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1101",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "شنبه  از 10:00 تا 12:15",
    classExam: "1403/04/04 از 10:30 تا 12:30",
    teacher: "سحر محمدرضابیگی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1418",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "69",
    courseCode: "3762131982",
    courseName: "زیست شناسی عمومی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1100",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "49",
    submitted: "",
    classTime: "شنبه  از 13:00 تا 15:15",
    classExam: "1403/04/04 از 10:30 تا 12:30",
    teacher: "سحر محمدرضابیگی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1418",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "95",
    courseCode: "6117172880",
    courseName: "ساختمان داده هاوالگوریتمها",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "7073",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "پنج شنبه  از 16:15 تا 19:15",
    classExam: "1403/04/03 از 08:00 تا 10:00",
    teacher: "حمید شاهوردی طرخورانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1205",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "96",
    courseCode: "6117172880",
    courseName: "ساختمان داده هاوالگوریتمها",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "7072",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "پنج شنبه  از 13:00 تا 16:00",
    classExam: "1403/04/03 از 08:00 تا 10:00",
    teacher: "حمید شاهوردی طرخورانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1205",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "17",
    courseCode: "6033135451",
    courseName: "شبکه‌های کامپیوتری",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "3696",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "3",
    submitted: "",
    classTime: "دوشنبه  از 15:30 تا 17:45",
    classExam: "1403/04/14 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "82",
    courseCode: "6117135451",
    courseName: "شبکه‌های کامپیوتری",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7087",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "31",
    submitted: "",
    classTime: "دوشنبه  از 15:30 تا 17:45",
    classExam: "1403/04/14 از 13:30 تا 15:30",
    teacher: "علی محمد مبصر آزاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1215",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "83",
    courseCode: "6117135451",
    courseName: "شبکه‌های کامپیوتری",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7086",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "دوشنبه  از 18:00 تا 20:15",
    classExam: "1403/04/14 از 13:30 تا 15:30",
    teacher: "علی محمد مبصر آزاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "34",
    courseCode: "1393138058",
    courseName: "طراحی و تحلیل الگوریتمها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "4554",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "10",
    submitted: "",
    classTime: "پنج شنبه  از 18:00 تا 20:15",
    classExam: "1403/04/02 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "92",
    courseCode: "6117138058",
    courseName: "طراحی و تحلیل الگوریتمها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7078",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "35",
    submitted: "",
    classTime: "پنج شنبه  از 18:00 تا 20:15",
    classExam: "1403/04/02 از 13:30 تا 15:30",
    teacher: "کمال پایکن",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1206",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "3",
    courseCode: "6117141750",
    courseName: "فیزیک عمومی ( 1 )",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "4214",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "سه شنبه  از 10:00 تا 12:15",
    classExam: "1403/04/07 از 10:30 تا 12:30",
    teacher: "فرناز حسین زاده",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1210",
    licence: "نيمسال ورود[نیمسال دوم سال تحصیلی 1403-1402]",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "4",
    courseCode: "6117141750",
    courseName: "فیزیک عمومی ( 1 )",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "4142",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "سه شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/07 از 10:30 تا 12:30",
    teacher: "فرناز حسین زاده",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1210",
    licence: "نيمسال ورود[نیمسال دوم سال تحصیلی 1403-1402]",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "53",
    courseCode: "6117141750",
    courseName: "فیزیک عمومی ( 1 )",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1340",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "شنبه  از 10:00 تا 12:15",
    classExam: "1403/04/07 از 10:30 تا 12:30",
    teacher: "راضیه صادقی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "54",
    courseCode: "6117141750",
    courseName: "فیزیک عمومی ( 1 )",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1339",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/07 از 10:30 تا 12:30",
    teacher: "راضیه صادقی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "55",
    courseCode: "6117141750",
    courseName: "فیزیک عمومی ( 1 )",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1336",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "48",
    submitted: "",
    classTime: "چهارشنبه  از 07:30 تا 09:45",
    classExam: "1403/04/07 از 10:30 تا 12:30",
    teacher: "آرش رضایی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1401",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "60",
    courseCode: "6117141759",
    courseName: "فیزیک عمومی 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1215",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "41",
    submitted: "",
    classTime: "پنج شنبه  از 10:00 تا 12:15",
    classExam: "1403/04/13 از 10:30 تا 12:30",
    teacher: "امیرهوشنگ رمضانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "61",
    courseCode: "6117141759",
    courseName: "فیزیک عمومی 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1214",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "41",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/13 از 10:30 تا 12:30",
    teacher: "امیرهوشنگ رمضانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "62",
    courseCode: "6117141759",
    courseName: "فیزیک عمومی 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1213",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "41",
    submitted: "",
    classTime: "دوشنبه  از 13:00 تا 15:15",
    classExam: "1403/04/13 از 10:30 تا 12:30",
    teacher: "ژاله ابراهیمی نژاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "63",
    courseCode: "6117141759",
    courseName: "فیزیک عمومی 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1212",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "42",
    submitted: "",
    classTime: "دوشنبه  از 10:00 تا 12:15",
    classExam: "1403/04/13 از 10:30 تا 12:30",
    teacher: "ژاله ابراهیمی نژاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "70",
    courseCode: "6117141759",
    courseName: "فیزیک عمومی 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1097",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "0",
    submitted: "",
    classTime: "",
    classExam: "1403/04/13 از 10:30 تا 12:30",
    teacher: "امیرهوشنگ رمضانی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "71",
    courseCode: "6117141759",
    courseName: "فیزیک عمومی 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1096",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "30",
    submitted: "",
    classTime: "دوشنبه  از 15:30 تا 17:45",
    classExam: "1403/04/13 از 10:30 تا 12:30",
    teacher: "پیام مهدی پورکلدیانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "72",
    courseCode: "6117141759",
    courseName: "فیزیک عمومی 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1095",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "42",
    submitted: "",
    classTime: "دوشنبه  از 13:00 تا 15:15",
    classExam: "1403/04/13 از 10:30 تا 12:30",
    teacher: "سمیه عسگری",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "73",
    courseCode: "6117141759",
    courseName: "فیزیک عمومی 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1094",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح دانشکده",
    minCapacity: "",
    maxCapacity: "41",
    submitted: "",
    classTime: "دوشنبه  از 10:00 تا 12:15",
    classExam: "1403/04/13 از 10:30 تا 12:30",
    teacher: "سمیه عسگری",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "74",
    courseCode: "6117141759",
    courseName: "فیزیک عمومی 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1093",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 15:30 تا 17:45",
    classExam: "1403/04/13 از 10:30 تا 12:30",
    teacher: "امیرهوشنگ رمضانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "25",
    courseCode: "6033160854",
    courseName: "کامپایلر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "9636",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "15",
    submitted: "",
    classTime: "سه شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/03 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "36",
    courseCode: "1393161581",
    courseName: "کمپایلر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "1221",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "10",
    submitted: "",
    classTime: "سه شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/03 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "37",
    courseCode: "1393161581",
    courseName: "کمپایلر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "3223",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "10",
    submitted: "",
    classTime: "سه شنبه  از 10:00 تا 12:15",
    classExam: "1403/04/03 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "26",
    courseCode: "1393142462",
    courseName: "گرافیک‌ کامپیوتری‌",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7989",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "2",
    submitted: "",
    classTime: "دوشنبه  از 15:30 تا 17:45",
    classExam: "1403/04/03 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "23",
    courseCode: "6033144224",
    courseName: "مباحثی در علوم کامپیوتر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "5263",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "6",
    submitted: "",
    classTime: "سه شنبه  از 18:00 تا 20:15",
    classExam: "1403/04/10 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "2",
    courseCode: "6033144407",
    courseName: "مبانی آنالیز ریاضی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "9635",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "15",
    submitted: "",
    classTime: "شنبه  از 16:15 تا 18:30",
    classExam: "1403/04/07 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "30",
    courseCode: "6117144407",
    courseName: "مبانی آنالیز ریاضی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "8963",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "10",
    submitted: "",
    classTime: "شنبه  از 16:15 تا 18:30",
    classExam: "1403/04/07 از 13:30 تا 15:30",
    teacher: "حسام محزون",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1211",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "21",
    courseCode: "6033144408",
    courseName: "مبانی آنالیزعددی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "3696",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "5",
    submitted: "",
    classTime: "دوشنبه  از 18:00 تا 20:15",
    classExam: "1403/04/06 از 13:30 تا 15:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "5",
    courseCode: "6117144297",
    courseName: "مبانی احتمال",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "2727",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "سه شنبه  از 15:30 تا 17:45",
    classExam: "1403/04/12 از 10:30 تا 12:30",
    teacher: "آرش نبی زاده",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1210",
    licence: "نيمسال ورود[نیمسال دوم سال تحصیلی 1403-1402]",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "22",
    courseCode: "6033144297",
    courseName: "مبانی احتمال",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7886",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "2",
    submitted: "",
    classTime: "چهارشنبه  از 18:00 تا 20:15",
    classExam: "1403/04/12 از 10:30 تا 12:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "35",
    courseCode: "6033144297",
    courseName: "مبانی احتمال",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "5225",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "6",
    submitted: "",
    classTime: "سه شنبه  از 15:30 تا 17:45",
    classExam: "1403/04/12 از 10:30 تا 12:30",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "91",
    courseCode: "6117144297",
    courseName: "مبانی احتمال",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7080",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "سه شنبه  از 13:00 تا 15:15",
    classExam: "1403/04/12 از 10:30 تا 12:30",
    teacher: "آرش نبی زاده",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1210",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "50",
    courseCode: "6117144838",
    courseName: "مبانی جبر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7135",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "دوشنبه  از 13:00 تا 15:15",
    classExam: "1403/04/13 از 08:00 تا 10:00",
    teacher: "امیر موسیوند",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1206",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "6",
    courseCode: "6117145941",
    courseName: "مبانی کامپیوتر و برنامه‌سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7412",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "دوشنبه  از 15:30 تا 17:45",
    classExam: "1403/04/02 از 08:00 تا 10:00",
    teacher: "دکتر اباصلت بداغی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1210",
    licence: "نيمسال ورود[نیمسال دوم سال تحصیلی 1403-1402]",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "7",
    courseCode: "6117145941",
    courseName: "مبانی کامپیوتر و برنامه‌سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "5632",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "دوشنبه  از 18:00 تا 20:15",
    classExam: "1403/04/02 از 08:00 تا 10:00",
    teacher: "دکتر اباصلت بداغی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1210",
    licence: "نيمسال ورود[نیمسال دوم سال تحصیلی 1403-1402]",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "88",
    courseCode: "6117145941",
    courseName: "مبانی کامپیوتر و برنامه‌سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7083",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "پنج شنبه  از 13:00 تا 15:15",
    classExam: "1403/04/02 از 08:00 تا 10:00",
    teacher: "دکتر اباصلت بداغی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1208",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "89",
    courseCode: "6117145941",
    courseName: "مبانی کامپیوتر و برنامه‌سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7082",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "46",
    submitted: "",
    classTime: "پنج شنبه  از 10:00 تا 12:15",
    classExam: "1403/04/02 از 08:00 تا 10:00",
    teacher: "دکتر اباصلت بداغی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1208",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "90",
    courseCode: "6117145941",
    courseName: "مبانی کامپیوتر و برنامه‌سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7081",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/02 از 08:00 تا 10:00",
    teacher: "دکتر اباصلت بداغی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1208",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "19",
    courseCode: "6033145678",
    courseName: "مبانی نظریه محاسبه",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "3562",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "3",
    submitted: "",
    classTime: "چهارشنبه  از 15:30 تا 17:45",
    classExam: "1403/04/11 از 08:00 تا 10:00",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "86",
    courseCode: "6117145678",
    courseName: "مبانی نظریه محاسبه",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7085",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "پنج شنبه  از 10:00 تا 12:15",
    classExam: "1403/04/11 از 08:00 تا 10:00",
    teacher: "مهدی آژینی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1210",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "87",
    courseCode: "6117145678",
    courseName: "مبانی نظریه محاسبه",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7084",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/11 از 08:00 تا 10:00",
    teacher: "مهدی آژینی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1210",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "100",
    courseCode: "6117145678",
    courseName: "مبانی نظریه محاسبه",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7068",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 18:00 تا 20:15",
    classExam: "1403/04/11 از 08:00 تا 10:00",
    teacher: "کمال پایکن",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1207",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "47",
    courseCode: "6117150350",
    courseName: "معادلات‌ دیفرانسیل‌",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7137",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "پنج شنبه  از 15:30 تا 17:45",
    classExam: "1403/04/07 از 13:30 تا 15:30",
    teacher: "کمال پایکن",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1206",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "48",
    courseCode: "6117150350",
    courseName: "معادلات‌ دیفرانسیل‌",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7136",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "پنج شنبه  از 13:00 تا 15:15",
    classExam: "1403/04/07 از 13:30 تا 15:30",
    teacher: "کمال پایکن",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1206",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "84",
    courseCode: "2661155491",
    courseName: "هوش مصنوعی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7089",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "پنج شنبه  از 10:00 تا 12:15",
    classExam: "1403/04/11 از 13:30 تا 15:30",
    teacher: "علی محمد مبصر آزاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1416",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    id: "85",
    courseCode: "2661155491",
    courseName: "هوش مصنوعی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "7088",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:45",
    classExam: "1403/04/11 از 13:30 تا 15:30",
    teacher: "علی محمد مبصر آزاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1412",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
];
