//@ts-nocheck

export const data = [
  {
    "": "33",
    courseCode: "6117105510",
    courseName: "اصول سیستم های عامل",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "10038",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 16:15 تا 19:15",
    classExam: "1403/10/22 از 13:30 تا 15:30",
    teacher: "محمد مهدی حسنی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "34",
    courseCode: "6117105510",
    courseName: "اصول سیستم های عامل",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "10037",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 13:00 تا 16:00",
    classExam: "1403/10/22 از 13:30 تا 15:30",
    teacher: "محمد مهدی حسنی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "18",
    courseCode: "6117105510",
    courseName: "اصول سیستم های عامل",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "10042",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 13:00 تا 16:00",
    classExam: "1403/10/29 از 13:30 تا 15:30",
    teacher: "مناف شریف زاده",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "3",
    courseCode: "6117105510",
    courseName: "اصول سیستم های عامل",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "10061",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "پنج شنبه  از 13:00 تا 16:00",
    classExam: "1403/10/22 از 13:30 تا 15:30",
    teacher: "مناف شریف زاده",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "62",
    courseCode: "6117105514",
    courseName: "اصول سیستمهای کامپیوتری",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "10013",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 16:15 تا 19:15",
    classExam: "1403/10/09 از 10:00 تا 12:00",
    teacher: "محمد مهدی حسنی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "63",
    courseCode: "6117105514",
    courseName: "اصول سیستمهای کامپیوتری",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "10012",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 13:00 تا 16:00",
    classExam: "1403/10/09 از 13:30 تا 15:30",
    teacher: "محمد مهدی حسنی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "19",
    courseCode: "2661105587",
    courseName: "اصول طراحی نرم افزار",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10041",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 10:00 تا 12:15",
    classExam: "1403/10/26 از 08:00 تا 10:00",
    teacher: "مناف شریف زاده",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "27",
    courseCode: "2661111667",
    courseName: "برنامه‌سازی پیشرفته",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10036",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 18:00 تا 20:15",
    classExam: "1403/10/23 از 08:00 تا 10:00",
    teacher: "امیر حسین اسدی مهماندوستی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "28",
    courseCode: "2661111667",
    courseName: "برنامه‌سازی پیشرفته",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10035",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 15:30 تا 17:45",
    classExam: "1403/10/23 از 08:00 تا 10:00",
    teacher: "امیر حسین اسدی مهماندوستی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "29",
    courseCode: "2661111667",
    courseName: "برنامه‌سازی پیشرفته",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10034",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 13:00 تا 15:15",
    classExam: "1403/10/23 از 08:00 تا 10:00",
    teacher: "امیر حسین اسدی مهماندوستی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "37",
    courseCode: "6117112863",
    courseName: "بهینه سازی خطی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10033",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 15:30 تا 17:45",
    classExam: "1403/10/19 از 13:30 تا 15:30",
    teacher: "سعید صیدانلو",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "38",
    courseCode: "6117112863",
    courseName: "بهینه سازی خطی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10032",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 13:00 تا 15:15",
    classExam: "1403/10/19 از 13:30 تا 15:30",
    teacher: "سعید صیدانلو",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "9",
    courseCode: "2661114001",
    courseName: "پایگاه‌داده‌ها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10052",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "20",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:45",
    classExam: "1403/10/02 از 08:00 تا 10:00",
    teacher: "مناف شریف زاده",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "8",
    courseCode: "1393114001",
    courseName: "پایگاه‌داده‌ها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10053",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "20",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:45",
    classExam: "1403/10/02 از 08:00 تا 10:00",
    teacher: "",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "13",
    courseCode: "6117121760",
    courseName: "جبر خطی عددی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10047",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 18:00 تا 20:15",
    classExam: "1403/10/01 از 13:30 تا 15:30",
    teacher: "مصطفی جانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "64",
    courseCode: "7000006697",
    courseName: "داده کاوی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10011",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 18:00 تا 20:15",
    classExam: "1403/05/14 از 10:00 تا 12:00",
    teacher: "سید محمود میرخان",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "80",
    courseCode: "6117165140",
    courseName: "ریاضی عمومی 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40050",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "48",
    submitted: "",
    classTime: "پنج شنبه  از 10:00 تا 12:15",
    classExam: "1403/10/09 از 10:30 تا 12:30",
    teacher: "احمدرضا حقیقی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1211",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "81",
    courseCode: "6117165140",
    courseName: "ریاضی عمومی 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40051",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "48",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:45",
    classExam: "1403/10/09 از 10:30 تا 12:30",
    teacher: "احمدرضا حقیقی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1211",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "25",
    courseCode: "55001",
    courseName: "ریاضیات پایه(پیش نیاز دانشگاهی)",
    courseType: "نظري",
    theoreticaUnits: "2",
    practicalUnits: "0",
    classCode: "50091",
    className: "استاد مریم صالح نژاد",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "يكشنبه  از 09:15 تا 10:45",
    classExam: "1403/10/11 از 10:30 تا 12:30",
    teacher: "مژگان علی عسگری",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1215",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "26",
    courseCode: "55001",
    courseName: "ریاضیات پایه(پیش نیاز دانشگاهی)",
    courseType: "نظري",
    theoreticaUnits: "2",
    practicalUnits: "0",
    classCode: "50090",
    className: "استاد: مریم صالح نژاد",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "يكشنبه  از 07:30 تا 09:00",
    classExam: "1403/10/11 از 10:30 تا 12:30",
    teacher: "مژگان علی عسگری",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1215",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "24",
    courseCode: "55001",
    courseName: "ریاضیات پایه(پیش نیاز دانشگاهی)",
    courseType: "نظري",
    theoreticaUnits: "2",
    practicalUnits: "0",
    classCode: "50095",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "سه شنبه  از 18:00 تا 19:30",
    classExam: "1403/10/11 از 10:30 تا 12:30",
    teacher: "حسن نوری اصفهانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1215",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "47",
    courseCode: "55001",
    courseName: "ریاضیات پایه(پیش نیاز دانشگاهی)",
    courseType: "نظري",
    theoreticaUnits: "2",
    practicalUnits: "0",
    classCode: "50076",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "پنج شنبه  از 11:00 تا 12:15",
    classExam: "1403/10/11 از 10:30 تا 12:30",
    teacher: "سمانه پرواز",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1208",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "48",
    courseCode: "55001",
    courseName: "ریاضیات پایه(پیش نیاز دانشگاهی)",
    courseType: "نظري",
    theoreticaUnits: "2",
    practicalUnits: "0",
    classCode: "50075",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "پنج شنبه  از 09:15 تا 10:45",
    classExam: "1403/10/11 از 10:30 تا 12:30",
    teacher: "سمانه پرواز",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1208",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "49",
    courseCode: "55001",
    courseName: "ریاضیات پایه(پیش نیاز دانشگاهی)",
    courseType: "نظري",
    theoreticaUnits: "2",
    practicalUnits: "0",
    classCode: "50074",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:00",
    classExam: "1403/10/11 از 10:30 تا 12:30",
    teacher: "سمانه پرواز",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1208",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "50",
    courseCode: "2590129864",
    courseName: "ریاضیات عمومی 3",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "10023",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 16:15 تا 19:15",
    classExam: "1403/10/16 از 10:30 تا 12:30",
    teacher: "حسام محزون",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "51",
    courseCode: "2590129864",
    courseName: "ریاضیات عمومی 3",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "10022",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 13:00 تا 16:00",
    classExam: "1403/10/16 از 10:30 تا 12:30",
    teacher: "حسام محزون",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "78",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40080",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "يكشنبه  از 18:00 تا 20:15",
    classExam: "1403/10/16 از 10:30 تا 12:30",
    teacher: "بهمن جلالی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1207",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "89",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40059",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "42",
    submitted: "",
    classTime: "يكشنبه  از 10:00 تا 12:15",
    classExam: "1403/10/16 از 10:30 تا 12:30",
    teacher: "عطیه مشهدی غلام",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1205",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "90",
    courseCode: "6117129685",
    courseName: "ریاضی‌عمومی‌ 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40058",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "42",
    submitted: "",
    classTime: "يكشنبه  از 07:30 تا 09:45",
    classExam: "1403/10/16 از 10:30 تا 12:30",
    teacher: "عطیه مشهدی غلام",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1205",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "7",
    courseCode: "2661130328",
    courseName: "ریز پردازنده 1",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10055",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "پنج شنبه  از 10:00 تا 12:15",
    classExam: "1403/10/03 از 10:00 تا 12:00",
    teacher: "مناف شریف زاده",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "22",
    courseCode: "6117131453",
    courseName: "زبان های برنامه سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10040",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/24 از 10:00 تا 12:00",
    teacher: "حسن برزگر",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "23",
    courseCode: "6117131453",
    courseName: "زبان های برنامه سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10039",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/24 از 10:30 تا 12:30",
    teacher: "حسن برزگر",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "30",
    courseCode: "3762131982",
    courseName: "زیست شناسی عمومی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "50083",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "30",
    submitted: "",
    classTime: "سه شنبه  از 10:00 تا 12:15",
    classExam: "1403/10/12 از 10:30 تا 12:30",
    teacher: "ارا منطقي تفرشي",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1207",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "31",
    courseCode: "3762131982",
    courseName: "زیست شناسی عمومی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "50082",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "30",
    submitted: "",
    classTime: "سه شنبه  از 07:30 تا 09:45",
    classExam: "1403/10/12 از 10:30 تا 12:30",
    teacher: "ارا منطقي تفرشي",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1207",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "16",
    courseCode: "6117172880",
    courseName: "ساختمان داده هاوالگوریتمها",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "10044",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 15:30 تا 18:30",
    classExam: "1403/10/27 از 13:30 تا 15:30",
    teacher: "کمال پایکن",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "1",
    courseCode: "6117172880",
    courseName: "ساختمان داده هاوالگوریتمها",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "10063",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "پنج شنبه  از 16:15 تا 19:15",
    classExam: "1403/10/27 از 13:30 تا 15:30",
    teacher: "کمال پایکن",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "2",
    courseCode: "6117172880",
    courseName: "ساختمان داده هاوالگوریتمها",
    courseType: "نظري",
    theoreticaUnits: "4",
    practicalUnits: "0",
    classCode: "10062",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "پنج شنبه  از 13:00 تا 16:00",
    classExam: "1403/10/27 از 13:30 تا 15:30",
    teacher: "کمال پایکن",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "74",
    courseCode: "6117135451",
    courseName: "شبکه‌های کامپیوتری",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10005",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 18:00 تا 20:15",
    classExam: "1403/10/02 از 10:00 تا 12:00",
    teacher: "علی محمد مبصر آزاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "75",
    courseCode: "6117135451",
    courseName: "شبکه‌های کامپیوتری",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10004",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/01 از 10:00 تا 12:00",
    teacher: "علی محمد مبصر آزاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "4",
    courseCode: "6117138058",
    courseName: "طراحی و تحلیل الگوریتمها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10060",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "پنج شنبه  از 18:00 تا 20:15",
    classExam: "1403/05/04 از 08:00 تا 10:00",
    teacher: "حمید شاهوردی طرخورانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "5",
    courseCode: "6117138058",
    courseName: "طراحی و تحلیل الگوریتمها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10058",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "پنج شنبه  از 15:30 تا 17:45",
    classExam: "1403/10/04 از 13:30 تا 15:30",
    teacher: "حمید شاهوردی طرخورانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "6",
    courseCode: "6117138058",
    courseName: "طراحی و تحلیل الگوریتمها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10056",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "پنج شنبه  از 13:00 تا 15:15",
    classExam: "1403/10/04 از 13:30 تا 15:30",
    teacher: "حمید شاهوردی طرخورانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "87",
    courseCode: "6117141750",
    courseName: "فیزیک عمومی ( 1 )",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40057",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "42",
    submitted: "",
    classTime: "يكشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/15 از 10:30 تا 12:30",
    teacher: "ژاله ابراهیمی نژاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1205",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "85",
    courseCode: "6117141750",
    courseName: "فیزیک عمومی ( 1 )",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40055",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "يكشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/15 از 10:30 تا 12:30",
    teacher: "سمیه عسگری",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1206",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "88",
    courseCode: "6117141750",
    courseName: "فیزیک عمومی ( 1 )",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40060",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "42",
    submitted: "",
    classTime: "يكشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/15 از 10:30 تا 12:30",
    teacher: "ژاله ابراهیمی نژاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1205",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "86",
    courseCode: "6117141750",
    courseName: "فیزیک عمومی ( 1 )",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40056",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "يكشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/15 از 10:30 تا 12:30",
    teacher: "سمیه عسگری",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1206",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "82",
    courseCode: "6117141750",
    courseName: "فیزیک عمومی ( 1 )",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40052",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "سه شنبه  از 13:00 تا 15:15",
    classExam: "1403/10/15 از 10:30 تا 12:30",
    teacher: "ژاله ابراهیمی نژاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1206",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "83",
    courseCode: "6117141750",
    courseName: "فیزیک عمومی ( 1 )",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40053",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "دوشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/15 از 10:30 تا 12:30",
    teacher: "ژاله ابراهیمی نژاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1206",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "84",
    courseCode: "6117141759",
    courseName: "فیزیک عمومی 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40054",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "يكشنبه  از 18:00 تا 20:15",
    classExam: "1403/10/18 از 10:30 تا 12:30",
    teacher: "لعیا دژم",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1206",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "79",
    courseCode: "6117141759",
    courseName: "فیزیک عمومی 2",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "40049",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "45",
    submitted: "",
    classTime: "شنبه  از 18:00 تا 20:15",
    classExam: "1403/10/18 از 10:30 تا 12:30",
    teacher: "حسین میقانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1207",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "20",
    courseCode: "6117160854",
    courseName: "کامپایلر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10042",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 07:30 تا 09:45",
    classExam: "1403/10/25 از 13:30 تا 15:30",
    teacher: "مناف شریف زاده",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "14",
    courseCode: "6117142462",
    courseName: "گرافیک‌ کامپیوتری‌",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10046",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/29 از 13:30 تا 15:30",
    teacher: "مصطفی جانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "15",
    courseCode: "6117142462",
    courseName: "گرافیک‌ کامپیوتری‌",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10045",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/29 از 08:00 تا 10:00",
    teacher: "مصطفی جانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "65",
    courseCode: "6117144224",
    courseName: "مباحثی در علوم کامپیوتر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10011",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/08 از 10:00 تا 12:00",
    teacher: "سید محمود میرخان",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "52",
    courseCode: "6117144224",
    courseName: "مباحثی در علوم کامپیوتر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10022",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 18:00 تا 20:15",
    classExam: "1403/10/08 از 10:00 تا 12:00",
    teacher: "سید محمود میرخان",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "53",
    courseCode: "6117144224",
    courseName: "مباحثی در علوم کامپیوتر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10021",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/08 از 10:00 تا 12:00",
    teacher: "سید محمود میرخان",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "54",
    courseCode: "6117144224",
    courseName: "مباحثی در علوم کامپیوتر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10020",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/08 از 10:00 تا 12:00",
    teacher: "سید محمود میرخان",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "21",
    courseCode: "6117144224",
    courseName: "مباحثی در علوم کامپیوتر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10041",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 18:00 تا 20:15",
    classExam: "1403/10/08 از 10:00 تا 12:00",
    teacher: "حسن برزگر",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "57",
    courseCode: "6117144408",
    courseName: "مبانی آنالیزعددی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10017",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 18:00 تا 20:15",
    classExam: "1403/10/12 از 13:30 تا 15:30",
    teacher: "محمد غلامیان",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "58",
    courseCode: "6117144408",
    courseName: "مبانی آنالیزعددی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10016",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/12 از 13:30 تا 15:30",
    teacher: "محمد غلامیان",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "59",
    courseCode: "6117144408",
    courseName: "مبانی آنالیزعددی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10015",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/12 از 13:30 تا 15:30",
    teacher: "محمد غلامیان",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "41",
    courseCode: "2661144297",
    courseName: "مبانی احتمال",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10029",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "دوشنبه  از 18:00 تا 20:15",
    classExam: "1403/10/18 از 08:00 تا 10:00",
    teacher: "علی مالکی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "42",
    courseCode: "2661144297",
    courseName: "مبانی احتمال",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10028",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/18 از 08:00 تا 10:00",
    teacher: "علی مالکی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "43",
    courseCode: "2661144297",
    courseName: "مبانی احتمال",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10027",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/18 از 08:00 تا 10:00",
    teacher: "علی مالکی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "60",
    courseCode: "6033144759",
    courseName: "مبانی ترکیبات",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10014",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 10:00 تا 12:15",
    classExam: "1403/10/11 از 13:30 تا 15:30",
    teacher: "مرجان منصف",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "61",
    courseCode: "6033144759",
    courseName: "مبانی ترکیبات",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10013",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 07:30 تا 09:45",
    classExam: "1403/10/11 از 13:30 تا 15:30",
    teacher: "مرجان منصف",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "72",
    courseCode: "6117144838",
    courseName: "مبانی جبر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10006",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 10:00 تا 12:15",
    classExam: "1403/10/03 از 10:00 تا 12:00",
    teacher: "امیر موسیوند",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "73",
    courseCode: "6117144838",
    courseName: "مبانی جبر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10005",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 07:30 تا 09:45",
    classExam: "1403/10/03 از 10:00 تا 12:00",
    teacher: "امیر موسیوند",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "39",
    courseCode: "6117144838",
    courseName: "مبانی جبر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10031",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 10:00 تا 12:15",
    classExam: "1403/10/03 از 10:00 تا 12:00",
    teacher: "امیر موسیوند",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "40",
    courseCode: "6117144838",
    courseName: "مبانی جبر",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10030",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 07:30 تا 09:45",
    classExam: "1403/10/03 از 10:00 تا 12:00",
    teacher: "امیر موسیوند",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "35",
    courseCode: "6117145323",
    courseName: "مبانی علوم ریاضی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10035",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 10:00 تا 12:15",
    classExam: "1403/10/20 از 10:30 تا 12:30",
    teacher: "الهه شیرین کلام",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "36",
    courseCode: "6117145323",
    courseName: "مبانی علوم ریاضی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10034",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 07:30 تا 09:45",
    classExam: "1403/10/20 از 10:30 تا 12:30",
    teacher: "الهه شیرین کلام",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "44",
    courseCode: "6117145941",
    courseName: "مبانی کامپیوتر و برنامه‌سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10026",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 18:00 تا 20:15",
    classExam: "1403/10/17 از 08:00 تا 10:00",
    teacher: "ناصر پرگالی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "45",
    courseCode: "6117145941",
    courseName: "مبانی کامپیوتر و برنامه‌سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10025",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/17 از 08:00 تا 10:00",
    teacher: "ناصر پرگالی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "46",
    courseCode: "6117145941",
    courseName: "مبانی کامپیوتر و برنامه‌سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10024",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/17 از 08:00 تا 10:00",
    teacher: "ناصر پرگالی",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "10",
    courseCode: "6117145941",
    courseName: "مبانی کامپیوتر و برنامه‌سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10051",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "پنج شنبه  از 13:00 تا 15:15",
    classExam: "1403/10/17 از 08:00 تا 10:00",
    teacher: "دکتر اباصلت بداغی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "11",
    courseCode: "6117145941",
    courseName: "مبانی کامپیوتر و برنامه‌سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10050",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "پنج شنبه  از 10:00 تا 12:15",
    classExam: "1403/10/17 از 08:00 تا 10:00",
    teacher: "دکتر اباصلت بداغی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "12",
    courseCode: "6117145941",
    courseName: "مبانی کامپیوتر و برنامه‌سازی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10049",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "50",
    submitted: "",
    classTime: "پنج شنبه  از 07:30 تا 09:45",
    classExam: "1403/10/17 از 08:00 تا 10:00",
    teacher: "دکتر اباصلت بداغی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "55",
    courseCode: "6117145444",
    courseName: "مبانی ماتریسها و جبرخطی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10019",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 18:00 تا 20:15",
    classExam: "1403/10/12 از 10:00 تا 12:00",
    teacher: "مریم مزدارانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "56",
    courseCode: "6117145444",
    courseName: "مبانی ماتریسها و جبرخطی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10018",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "دوشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/12 از 10:00 تا 12:00",
    teacher: "مریم مزدارانی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "66",
    courseCode: "6117145577",
    courseName: "مبانی منطق و نظریه مجموعه ها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10010",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/05 از 10:00 تا 12:00",
    teacher: "الهه شیرین کلام",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "67",
    courseCode: "6117145577",
    courseName: "مبانی منطق و نظریه مجموعه ها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10009",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 10:00 تا 12:15",
    classExam: "1403/10/05 از 08:00 تا 10:00",
    teacher: "الهه شیرین کلام",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "68",
    courseCode: "6117145577",
    courseName: "مبانی منطق و نظریه مجموعه ها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10008",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 07:30 تا 09:45",
    classExam: "1403/10/05 از 13:30 تا 15:30",
    teacher: "الهه شیرین کلام",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "32",
    courseCode: "6117145577",
    courseName: "مبانی منطق و نظریه مجموعه ها",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10039",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "سه شنبه  از 13:00 تا 15:15",
    classExam: "1403/10/05 از 13:30 تا 15:30",
    teacher: "الهه شیرین کلام",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "17",
    courseCode: "6117145678",
    courseName: "مبانی نظریه محاسبه",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10043",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "چهارشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/26 از 08:00 تا 10:00",
    teacher: "کمال پایکن",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "69",
    courseCode: "6033147873",
    courseName: "مدارهای منطقی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10008",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 18:00 تا 20:15",
    classExam: "1403/10/04 از 08:00 تا 10:00",
    teacher: "ناصر پرگالی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1311",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "70",
    courseCode: "6033147873",
    courseName: "مدارهای منطقی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10007",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 15:30 تا 17:45",
    classExam: "1403/10/04 از 08:00 تا 10:00",
    teacher: "ناصر پرگالی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "71",
    courseCode: "6033147873",
    courseName: "مدارهای منطقی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10006",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/04 از 08:00 تا 10:00",
    teacher: "ناصر پرگالی",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1314",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "77",
    courseCode: "6117150350",
    courseName: "معادلات‌ دیفرانسیل‌",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10001",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "",
    classExam: "1403/10/24 از 10:00 تا 12:00",
    teacher: "محمد غلامیان",
    otherTeacher: "",
    location: "",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
  {
    "": "76",
    courseCode: "2661155491",
    courseName: "هوش مصنوعی",
    courseType: "نظري",
    theoreticaUnits: "3",
    practicalUnits: "0",
    classCode: "10003",
    className: "",
    maghtaEraeh: "كارشناسي پيوسته",
    presentationType: "حضوري",
    presentationLevel: "ارائه در سطح گروه آموزشی",
    minCapacity: "",
    maxCapacity: "40",
    submitted: "",
    classTime: "يكشنبه  از 13:00 تا 15:15",
    classExam: "1403/10/24 از 10:00 تا 12:00",
    teacher: "علی محمد مبصر آزاد",
    otherTeacher: "",
    location: "228 - تهران غرب-فنی-1312",
    licence: "",
    educationalGroup: "گروه آموزشي رياضيات و علوم کامپيوتر(2122814)",
    college: "228 - تهران غرب(228)",
    unit: "228 - تهران غرب(21228)",
    province: "21 - تهران(21)",
  },
];

export interface Course {
  "": number;
  courseCode: string;
  courseName: string;
  courseType: string;
  theoreticalUnits: string;
  practicalUnits: string;
  classCode: string;
  className: string;
  maghtaEraeh: string;
  presentationType: string;
  presentationLevel: string;
  minCapacity: string;
  maxCapacity: string;
  submitted: string;
  classTime: string;
  classExam: string;
  teacher: string;
  otherTeacher: string;
  location: string;
  licence: string;
  educationalGroup: string;
  college: string;
  unit: string;
  province: string;
  x?: string;
  y?: number[];
}

function parseClassTime(course: Course): Course | false {
  const classTime = course.classTime;

  if (!classTime) return false;

  const [day, timeRange] = classTime?.split("  از ");

  const [startTime, endTime] = timeRange?.split(" تا ");

  const date1 = startTime?.trim().split(":");
  const date2 = endTime?.trim().split(":");

  course.x = day?.trim();

  course.y = [
    new Date(2023, 0, 1, +date1[0], +date1[1]).getTime(),
    new Date(2023, 0, 1, +date2[0], +date2[1]).getTime(),
  ];

  return course;
}

export const courses = data.map((item) => parseClassTime(item)) as Course[];
